# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from inekf_msgs/State.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import inekf_msgs.msg
import std_msgs.msg

class State(genpy.Message):
  _md5sum = "e7343162f53e88be8c7489511184bffa"
  _type = "inekf_msgs/State"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Quaternion orientation
geometry_msgs/Vector3 velocity
geometry_msgs/Point position
float64[81] covariance
VectorWithId[] contacts
VectorWithId[] landmarks
geometry_msgs/Vector3 gyroscope_bias
geometry_msgs/Vector3 accelerometer_bias


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: inekf_msgs/VectorWithId
int32 id
geometry_msgs/Point position
"""
  __slots__ = ['header','orientation','velocity','position','covariance','contacts','landmarks','gyroscope_bias','accelerometer_bias']
  _slot_types = ['std_msgs/Header','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Point','float64[81]','inekf_msgs/VectorWithId[]','inekf_msgs/VectorWithId[]','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,orientation,velocity,position,covariance,contacts,landmarks,gyroscope_bias,accelerometer_bias

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(State, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.covariance is None:
        self.covariance = [0.] * 81
      if self.contacts is None:
        self.contacts = []
      if self.landmarks is None:
        self.landmarks = []
      if self.gyroscope_bias is None:
        self.gyroscope_bias = geometry_msgs.msg.Vector3()
      if self.accelerometer_bias is None:
        self.accelerometer_bias = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.orientation = geometry_msgs.msg.Quaternion()
      self.velocity = geometry_msgs.msg.Vector3()
      self.position = geometry_msgs.msg.Point()
      self.covariance = [0.] * 81
      self.contacts = []
      self.landmarks = []
      self.gyroscope_bias = geometry_msgs.msg.Vector3()
      self.accelerometer_bias = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.position.x, _x.position.y, _x.position.z))
      buff.write(_get_struct_81d().pack(*self.covariance))
      length = len(self.contacts)
      buff.write(_struct_I.pack(length))
      for val1 in self.contacts:
        _x = val1.id
        buff.write(_get_struct_i().pack(_x))
        _v1 = val1.position
        _x = _v1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.landmarks)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks:
        _x = val1.id
        buff.write(_get_struct_i().pack(_x))
        _v2 = val1.position
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_6d().pack(_x.gyroscope_bias.x, _x.gyroscope_bias.y, _x.gyroscope_bias.z, _x.accelerometer_bias.x, _x.accelerometer_bias.y, _x.accelerometer_bias.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.contacts is None:
        self.contacts = None
      if self.landmarks is None:
        self.landmarks = None
      if self.gyroscope_bias is None:
        self.gyroscope_bias = geometry_msgs.msg.Vector3()
      if self.accelerometer_bias is None:
        self.accelerometer_bias = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.position.x, _x.position.y, _x.position.z,) = _get_struct_10d().unpack(str[start:end])
      start = end
      end += 648
      self.covariance = _get_struct_81d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.contacts = []
      for i in range(0, length):
        val1 = inekf_msgs.msg.VectorWithId()
        start = end
        end += 4
        (val1.id,) = _get_struct_i().unpack(str[start:end])
        _v3 = val1.position
        _x = _v3
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.contacts.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks = []
      for i in range(0, length):
        val1 = inekf_msgs.msg.VectorWithId()
        start = end
        end += 4
        (val1.id,) = _get_struct_i().unpack(str[start:end])
        _v4 = val1.position
        _x = _v4
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.landmarks.append(val1)
      _x = self
      start = end
      end += 48
      (_x.gyroscope_bias.x, _x.gyroscope_bias.y, _x.gyroscope_bias.z, _x.accelerometer_bias.x, _x.accelerometer_bias.y, _x.accelerometer_bias.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_10d().pack(_x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.position.x, _x.position.y, _x.position.z))
      buff.write(self.covariance.tostring())
      length = len(self.contacts)
      buff.write(_struct_I.pack(length))
      for val1 in self.contacts:
        _x = val1.id
        buff.write(_get_struct_i().pack(_x))
        _v5 = val1.position
        _x = _v5
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      length = len(self.landmarks)
      buff.write(_struct_I.pack(length))
      for val1 in self.landmarks:
        _x = val1.id
        buff.write(_get_struct_i().pack(_x))
        _v6 = val1.position
        _x = _v6
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self
      buff.write(_get_struct_6d().pack(_x.gyroscope_bias.x, _x.gyroscope_bias.y, _x.gyroscope_bias.z, _x.accelerometer_bias.x, _x.accelerometer_bias.y, _x.accelerometer_bias.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.orientation is None:
        self.orientation = geometry_msgs.msg.Quaternion()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Vector3()
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.contacts is None:
        self.contacts = None
      if self.landmarks is None:
        self.landmarks = None
      if self.gyroscope_bias is None:
        self.gyroscope_bias = geometry_msgs.msg.Vector3()
      if self.accelerometer_bias is None:
        self.accelerometer_bias = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 80
      (_x.orientation.x, _x.orientation.y, _x.orientation.z, _x.orientation.w, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.position.x, _x.position.y, _x.position.z,) = _get_struct_10d().unpack(str[start:end])
      start = end
      end += 648
      self.covariance = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=81)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.contacts = []
      for i in range(0, length):
        val1 = inekf_msgs.msg.VectorWithId()
        start = end
        end += 4
        (val1.id,) = _get_struct_i().unpack(str[start:end])
        _v7 = val1.position
        _x = _v7
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.contacts.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.landmarks = []
      for i in range(0, length):
        val1 = inekf_msgs.msg.VectorWithId()
        start = end
        end += 4
        (val1.id,) = _get_struct_i().unpack(str[start:end])
        _v8 = val1.position
        _x = _v8
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.landmarks.append(val1)
      _x = self
      start = end
      end += 48
      (_x.gyroscope_bias.x, _x.gyroscope_bias.y, _x.gyroscope_bias.z, _x.accelerometer_bias.x, _x.accelerometer_bias.y, _x.accelerometer_bias.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
_struct_81d = None
def _get_struct_81d():
    global _struct_81d
    if _struct_81d is None:
        _struct_81d = struct.Struct("<81d")
    return _struct_81d
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
