// Generated by gencpp from file SegmentationMapping/ImageLabelDistribution.msg
// DO NOT EDIT!


#ifndef SEGMENTATIONMAPPING_MESSAGE_IMAGELABELDISTRIBUTION_H
#define SEGMENTATIONMAPPING_MESSAGE_IMAGELABELDISTRIBUTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float32MultiArray.h>

namespace SegmentationMapping
{
template <class ContainerAllocator>
struct ImageLabelDistribution_
{
  typedef ImageLabelDistribution_<ContainerAllocator> Type;

  ImageLabelDistribution_()
    : header()
    , distribution()  {
    }
  ImageLabelDistribution_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distribution(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::Float32MultiArray_<ContainerAllocator>  _distribution_type;
  _distribution_type distribution;





  typedef boost::shared_ptr< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> const> ConstPtr;

}; // struct ImageLabelDistribution_

typedef ::SegmentationMapping::ImageLabelDistribution_<std::allocator<void> > ImageLabelDistribution;

typedef boost::shared_ptr< ::SegmentationMapping::ImageLabelDistribution > ImageLabelDistributionPtr;
typedef boost::shared_ptr< ::SegmentationMapping::ImageLabelDistribution const> ImageLabelDistributionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator1> & lhs, const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distribution == rhs.distribution;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator1> & lhs, const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace SegmentationMapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7601bdc96663397412b61ff2686aaf0";
  }

  static const char* value(const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7601bdc96663397ULL;
  static const uint64_t static_value2 = 0x412b61ff2686aaf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SegmentationMapping/ImageLabelDistribution";
  }

  static const char* value(const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"std_msgs/Header            header\n"
"std_msgs/Float32MultiArray distribution\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float32[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distribution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageLabelDistribution_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::SegmentationMapping::ImageLabelDistribution_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distribution: ";
    s << std::endl;
    Printer< ::std_msgs::Float32MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.distribution);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEGMENTATIONMAPPING_MESSAGE_IMAGELABELDISTRIBUTION_H
