// Generated by gencpp from file inekf_msgs/KinematicsArray.msg
// DO NOT EDIT!


#ifndef INEKF_MSGS_MESSAGE_KINEMATICSARRAY_H
#define INEKF_MSGS_MESSAGE_KINEMATICSARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <inekf_msgs/Kinematics.h>

namespace inekf_msgs
{
template <class ContainerAllocator>
struct KinematicsArray_
{
  typedef KinematicsArray_<ContainerAllocator> Type;

  KinematicsArray_()
    : header()
    , frames()  {
    }
  KinematicsArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , frames(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::inekf_msgs::Kinematics_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::inekf_msgs::Kinematics_<ContainerAllocator> >::other >  _frames_type;
  _frames_type frames;





  typedef boost::shared_ptr< ::inekf_msgs::KinematicsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inekf_msgs::KinematicsArray_<ContainerAllocator> const> ConstPtr;

}; // struct KinematicsArray_

typedef ::inekf_msgs::KinematicsArray_<std::allocator<void> > KinematicsArray;

typedef boost::shared_ptr< ::inekf_msgs::KinematicsArray > KinematicsArrayPtr;
typedef boost::shared_ptr< ::inekf_msgs::KinematicsArray const> KinematicsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inekf_msgs::KinematicsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::inekf_msgs::KinematicsArray_<ContainerAllocator1> & lhs, const ::inekf_msgs::KinematicsArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.frames == rhs.frames;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::inekf_msgs::KinematicsArray_<ContainerAllocator1> & lhs, const ::inekf_msgs::KinematicsArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace inekf_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inekf_msgs::KinematicsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inekf_msgs::KinematicsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inekf_msgs::KinematicsArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b884fa68e050b5e1db84e96861a148f";
  }

  static const char* value(const ::inekf_msgs::KinematicsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b884fa68e050b5eULL;
  static const uint64_t static_value2 = 0x1db84e96861a148fULL;
};

template<class ContainerAllocator>
struct DataType< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inekf_msgs/KinematicsArray";
  }

  static const char* value(const ::inekf_msgs::KinematicsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Kinematics[] frames\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: inekf_msgs/Kinematics\n"
"int32 id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::inekf_msgs::KinematicsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.frames);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KinematicsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inekf_msgs::KinematicsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inekf_msgs::KinematicsArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "frames[]" << std::endl;
    for (size_t i = 0; i < v.frames.size(); ++i)
    {
      s << indent << "  frames[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::inekf_msgs::Kinematics_<ContainerAllocator> >::stream(s, indent + "    ", v.frames[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INEKF_MSGS_MESSAGE_KINEMATICSARRAY_H
