// Generated by gencpp from file inekf_msgs/LandmarkArray.msg
// DO NOT EDIT!


#ifndef INEKF_MSGS_MESSAGE_LANDMARKARRAY_H
#define INEKF_MSGS_MESSAGE_LANDMARKARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <inekf_msgs/VectorWithId.h>

namespace inekf_msgs
{
template <class ContainerAllocator>
struct LandmarkArray_
{
  typedef LandmarkArray_<ContainerAllocator> Type;

  LandmarkArray_()
    : header()
    , landmarks()  {
    }
  LandmarkArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , landmarks(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::inekf_msgs::VectorWithId_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::inekf_msgs::VectorWithId_<ContainerAllocator> >::other >  _landmarks_type;
  _landmarks_type landmarks;





  typedef boost::shared_ptr< ::inekf_msgs::LandmarkArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inekf_msgs::LandmarkArray_<ContainerAllocator> const> ConstPtr;

}; // struct LandmarkArray_

typedef ::inekf_msgs::LandmarkArray_<std::allocator<void> > LandmarkArray;

typedef boost::shared_ptr< ::inekf_msgs::LandmarkArray > LandmarkArrayPtr;
typedef boost::shared_ptr< ::inekf_msgs::LandmarkArray const> LandmarkArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inekf_msgs::LandmarkArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::inekf_msgs::LandmarkArray_<ContainerAllocator1> & lhs, const ::inekf_msgs::LandmarkArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.landmarks == rhs.landmarks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::inekf_msgs::LandmarkArray_<ContainerAllocator1> & lhs, const ::inekf_msgs::LandmarkArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace inekf_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inekf_msgs::LandmarkArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inekf_msgs::LandmarkArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inekf_msgs::LandmarkArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "785787915a1ac5c409c99b8e39adb3e0";
  }

  static const char* value(const ::inekf_msgs::LandmarkArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x785787915a1ac5c4ULL;
  static const uint64_t static_value2 = 0x09c99b8e39adb3e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inekf_msgs/LandmarkArray";
  }

  static const char* value(const ::inekf_msgs::LandmarkArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"VectorWithId[] landmarks\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: inekf_msgs/VectorWithId\n"
"int32 id\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::inekf_msgs::LandmarkArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.landmarks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandmarkArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inekf_msgs::LandmarkArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inekf_msgs::LandmarkArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "landmarks[]" << std::endl;
    for (size_t i = 0; i < v.landmarks.size(); ++i)
    {
      s << indent << "  landmarks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::inekf_msgs::VectorWithId_<ContainerAllocator> >::stream(s, indent + "    ", v.landmarks[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INEKF_MSGS_MESSAGE_LANDMARKARRAY_H
