// Generated by gencpp from file inekf_msgs/VectorWithId.msg
// DO NOT EDIT!


#ifndef INEKF_MSGS_MESSAGE_VECTORWITHID_H
#define INEKF_MSGS_MESSAGE_VECTORWITHID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace inekf_msgs
{
template <class ContainerAllocator>
struct VectorWithId_
{
  typedef VectorWithId_<ContainerAllocator> Type;

  VectorWithId_()
    : id(0)
    , position()  {
    }
  VectorWithId_(const ContainerAllocator& _alloc)
    : id(0)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::inekf_msgs::VectorWithId_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::inekf_msgs::VectorWithId_<ContainerAllocator> const> ConstPtr;

}; // struct VectorWithId_

typedef ::inekf_msgs::VectorWithId_<std::allocator<void> > VectorWithId;

typedef boost::shared_ptr< ::inekf_msgs::VectorWithId > VectorWithIdPtr;
typedef boost::shared_ptr< ::inekf_msgs::VectorWithId const> VectorWithIdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::inekf_msgs::VectorWithId_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::inekf_msgs::VectorWithId_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::inekf_msgs::VectorWithId_<ContainerAllocator1> & lhs, const ::inekf_msgs::VectorWithId_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::inekf_msgs::VectorWithId_<ContainerAllocator1> & lhs, const ::inekf_msgs::VectorWithId_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace inekf_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::inekf_msgs::VectorWithId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::inekf_msgs::VectorWithId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inekf_msgs::VectorWithId_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::inekf_msgs::VectorWithId_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inekf_msgs::VectorWithId_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::inekf_msgs::VectorWithId_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::inekf_msgs::VectorWithId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "862d4cb04abf0384b83634e27574137f";
  }

  static const char* value(const ::inekf_msgs::VectorWithId_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x862d4cb04abf0384ULL;
  static const uint64_t static_value2 = 0xb83634e27574137fULL;
};

template<class ContainerAllocator>
struct DataType< ::inekf_msgs::VectorWithId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "inekf_msgs/VectorWithId";
  }

  static const char* value(const ::inekf_msgs::VectorWithId_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::inekf_msgs::VectorWithId_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::inekf_msgs::VectorWithId_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::inekf_msgs::VectorWithId_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VectorWithId_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::inekf_msgs::VectorWithId_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::inekf_msgs::VectorWithId_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INEKF_MSGS_MESSAGE_VECTORWITHID_H
